export default {
  SAVE_FETCHED_FILTERS: 'SAVE_FETCHED_FILTERS',
  SELECT_FILTERS: 'SELECT_FILTERS',
  SIDEBAR_TOGGLE: 'SIDEBAR_TOGGLE',
  SET_CONTENT_LANGUAGE: 'SET_CONTENT_LANGUAGE',
  DARK_THEME_TOGGLE: 'DARK_THEME_TOGGLE',
  SAVE_SEARCH_QUERY: 'SAVE_SEARCH_QUERY',
  SAVE_RETAIL_CHAINS: 'SAVE_RETAIL_CHAINS',
  SET_HOMEPAGE_LOADING: 'SET_HOMEPAGE_LOADING',
};
